# Workflow to run a scheduled job

name: Scheduled Job

on:
  schedule:
    - cron: '0 5 * * *' # Runs at midnight EST without DST

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: echo 'Running scheduled job'