name: Update Number of the Hour

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Run num_of_hour script
      run: cargo run --release

    - name: Commit and push changes
      run: |
        git config --global user.name 'Zander Lewis'
        git config --global user.email 'zander@zanderlewis.dev'
        git add README.md
        git commit -m "[BOT] Update number of the hour"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
