name: Stats/Age

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # every hour
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick
    - name: Generate README.md
      uses: teoxoy/profile-readme-stats@v3
      with:
        token: ${{ secrets.USER_TOKEN }}
    - name: Update README.md (STATS)
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add .
        git commit -m "Update README"
        fi
    - name: Calculate age and update README
      run: |
        export DISPLAY=:99
        nohup Xvfb :99 -screen 0 1024x768x24 &
        python -c "
        import datetime
        birth_date = datetime.date(2008, 9, 14)
        today = datetime.date.today()
        age = today.year - birth_date.year - ((today.month, today.day) < (birth_date.month, birth_date.day))
        with open('TEMPLATE.md', 'r') as template_file:
            template_content = template_file.read()
        updated_content = template_content.replace('{{age}}', str(age))
        with open('README.md', 'w') as readme_file:
            readme_file.write(updated_content)
        print(f'Calculated Age: {age}')
        "
    - name: Update README.md (AGE)
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add .
        git commit -m "Update README"
        git push
        fi